/**
 * Zero-Knowledge Proof Service
 * Generates and verifies zk-SNARK proofs for file ownership using snarkjs,
 * against circuits compiled from zkp/circuits/ownership.circom.
 *
 * The circuit proves knowledge of a secret "ownerSecret" whose Poseidon/keccak
 * hash matches a public commitment stored on-chain, WITHOUT revealing the
 * secret itself. This lets a user prove they own a file without exposing
 * private key material or the raw file content.
 */
const path = require('path');
const snarkjs = require('snarkjs');
const config = require('../config/config');

const wasmPath = path.resolve(__dirname, config.zkp.wasmPath);
const zkeyPath = path.resolve(__dirname, config.zkp.zkeyPath);
const vkeyPath = path.resolve(__dirname, config.zkp.vkeyPath);

/**
 * Generate a Groth16 proof for the ownership circuit.
 * @param {object} input - circuit input signals, e.g. { ownerSecret, commitment }
 * @returns {Promise<{proof: object, publicSignals: string[]}>}
 */
async function generateProof(input) {
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    wasmPath,
    zkeyPath
  );
  return { proof, publicSignals };
}

/**
 * Verify a Groth16 proof against the verification key.
 * @param {object} proof
 * @param {string[]} publicSignals
 * @returns {Promise<boolean>}
 */
async function verifyProof(proof, publicSignals) {
  const vKey = require(vkeyPath);
  return snarkjs.groth16.verify(vKey, publicSignals, proof);
}

/**
 * Format a snarkjs proof into the calldata shape expected by the
 * on-chain Verifier.sol contract (auto-generated by snarkjs `zkey export solidityverifier`).
 * @param {object} proof
 * @param {string[]} publicSignals
 */
async function formatCalldata(proof, publicSignals) {
  const calldata = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
  const parsed = JSON.parse(`[${calldata}]`);
  return { a: parsed[0], b: parsed[1], c: parsed[2], input: parsed[3] };
}

module.exports = { generateProof, verifyProof, formatCalldata };
